graphhopper:
  datareader.file: batangas.pbf
  gtfs.file: gtfs.zip
  # Local folder used by graphhopper to store its data
  graph.location: graph-cache

  profiles:
    - name: foot
      custom_model_files:
        - foot.json
      # optionally add
      #  - foot_elevation.json

  import.osm.ignored_highways: motorway,trunk
  graph.encoded_values: foot_access, foot_average_speed, foot_priority, foot_road_access, hike_rating, mtb_rating, country, road_class, road_environment

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
  admin_connectors:
    - type: http
      port: 8990
      bind_host: 0.0.0.0
